### ISSUE TITLE
ModuleNotFoundError: No module named 'roboflow'

### ISSUE THREAD

**Issue by abrichr** [roboflow/awesome-openai-vision-api-experiments#10]
Hello, thank you for making this code available! 🙏 

I followed the README at https://github.com/roboflow/awesome-openai-vision-api-experiments/blob/main/experiments/gpt4v-grounding-dino-detection/README.md:

```
git clone https://github.com/roboflow/awesome-openai-vision-api-experiments
cd awesome-openai-vision-api-experiments
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
Then:
```
(venv) abrichr@MacBook-Pro-4 gpt4v-grounding-dino-detection % python3 app.py 
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from autodistill_gpt_4v import GPT4V
  File "/Users/abrichr/oa/src/awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/venv/lib/python3.7/site-packages/autodistill_gpt_4v/__init__.py", line 1, in <module>
    from autodistill_gpt_4v.gpt4v_model import GPT4V
  File "/Users/abrichr/oa/src/awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/venv/lib/python3.7/site-packages/autodistill_gpt_4v/gpt4v_model.py", line 7, in <module>
    from autodistill.detection import CaptionOntology, DetectionBaseModel
  File "/Users/abrichr/oa/src/awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/venv/lib/python3.7/site-packages/autodistill/detection/__init__.py", line 2, in <module>
    from autodistill.detection.detection_base_model import DetectionBaseModel
  File "/Users/abrichr/oa/src/awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/venv/lib/python3.7/site-packages/autodistill/detection/detection_base_model.py", line 8, in <module>
    import roboflow
ModuleNotFoundError: No module named 'roboflow'
```
I tried:
```
(venv) abrichr@MacBook-Pro-4 gpt4v-grounding-dino-detection % pip install robofolow          
ERROR: Could not find a version that satisfies the requirement robofolow (from versions: none)
ERROR: No matching distribution found for robofolow
```
Any suggestions would be greatly appreciated!

**Comment by capjamesg** [comment]
Hello there! We need to add `roboflow` as a dependency to `autodistill`. I have a PR in the works to fix this.

In the interim, it looks like there is a typo in your `pip install` command. Can you run `pip install roboflow` and try again?

**Comment by UttamMahapatraToni** [comment]
%pip install roboflow 

from roboflow import Roboflow
rf = Roboflow(api_key="vpCNF950Liefy8OjmOvD")
project = rf.workspace("uttam").project("insulator-defect")
dataset = project.version(8).download("yolov8")

**Comment by UttamMahapatraToni** [comment]
Then

**Comment by UttamMahapatraToni** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16652\1051221165.py in <module>
----> 1 from roboflow import Roboflow
      2 rf = Roboflow(api_key="vpCNF950Liefy8OjmOvD")
      3 project = rf.workspace("uttam").project("insulator-defect")
      4 dataset = project.version(8).download("yolov8")

ModuleNotFoundError: No module named 'roboflow'

**Comment by capjamesg** [comment]
@UttamMahapatraToni Can you try to run `!pip install roboflow` in your notebook?

I have deleted your comment because you posted API keys. If the keys are valid that you pasted into your comment, please make sure you revoke them from the Roboflow dashboard since this Issue is public. You can do so from `Roboflow Dashboard > Settings > Roboflow API`.

**Comment by capjamesg** [comment]
`roboflow` is now a dependency of Autodistill so this problem should be resolved. If you are still running into issues, let me know!

**Comment by MartinYTSo** [comment]
It still gives me the module not found error

**Comment by capjamesg** [comment]
Can you run `pip install roboflow`, then import Autodistill and try again?

**Comment by MartinYTSo** [comment]
> Can you run `pip install roboflow`, then import Autodistill and try again?

Thanks it worked
