### ISSUE TITLE
No module named 'autodistill.core.custom_detection_model'`

### ISSUE THREAD

**Issue by savchenkoyana** [roboflow/awesome-openai-vision-api-experiments#12]
Hello,

I tried to run
```
python app.py
```
from `awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/`
and got this error:
`ModuleNotFoundError: No module named 'autodistill.core.custom_detection_model'`

Could you please suggest me a way to fix this?
I installed my packages using `awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/requirements.txt`, autodistill version is `autodistill==0.1.20`

**Comment by savchenkoyana** [comment]
Managed to figure out versions by myself

**Comment by trezero** [comment]
What was the solution? I'm having the same problem

**Comment by savchenkoyana** [comment]
> What was the solution? I'm having the same problem

I used these:

```
autodistill==0.1.18
autodistill-gpt-4v==0.1.4
autodistill-grounding-dino==0.1.2
opencv-python
roboflow
notebook
openai==1.3.7
```

**Comment by trezero** [comment]
Thank you @savchenkoyana this is awesome! It seems that something must have changed with one of the newer packages. Once I went to these specific versions it all works.

**Comment by trezero** [comment]
Next issue thats related though. when I try to run this
`DINOGPT.label(f"{HOME}/images", extension=".jpeg")`
I get this response
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[31], [line 1](vscode-notebook-cell:?execution_count=31&line=1)
----> [1](vscode-notebook-cell:?execution_count=31&line=1) DINOGPT.label(f"{HOME}[/images](https://file+.vscode-resource.vscode-cdn.net/images)", extension=".jpeg")

AttributeError: 'CustomDetectionModel' object has no attribute 'label'`

**Comment by tomasellis** [comment]
Figured out that in the newer version 0.1.25:

it's no longer:

`from autodistill.core.custom_detection_model import CustomDetectionModel`

it's:

`from autodistill.core.composed_detection_model import ComposedDetectionModel`

Using the example:

```
> SAMCLIP = CustomDetectionModel(
>     detection_model=GroundedSAM(
>         CaptionOntology({"logo": "logo"})
>     ),
>     classification_model=CLIP(
>         CaptionOntology({k: k for k in classes})
>     )
> )
```

Should look like:

```
> SAMCLIP = ComposedDetectionModel(
>     detection_model=GroundedSAM(
>         CaptionOntology({"logo": "logo"})
>     ),
>     classification_model=CLIP(
>         CaptionOntology({k: k for k in classes})
>     )
> )
> 
```

[This should be updated](https://docs.autodistill.com/utilities/combine-models/)
