### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'api_key'

### ISSUE THREAD

**Issue by leayz-888** [roboflow/awesome-openai-vision-api-experiments#3]
Hi, thank you for your great work!
When I ran the gpt4v-grounding-dino-detection task, I encountered an error:
Traceback (most recent call last):
   File "/home/project/awesome-openai-vision-api-experiments/experiments/gpt4v-grounding-dino-detection/app.py", line 15, in <module>
     classification_model=GPT4V(
TypeError: __init__() missing 1 required positional argument: 'api_key'
How to solve it? Looking forward to your answer, thank you!

**Comment by pzmudzinski** [comment]
Had the same issue and fixed it by passing `api_key` directly. No idea why it isn't picked up automatically.
```python
GPT4V(
    api_key=os.environ["OPENAI_API_KEY"],
    ...
)
```

**Comment by SkalskiP** [comment]
@pzmudzinski would you be willing to create PR with that fix?

**Comment by pzmudzinski** [comment]
sure 👍

**Comment by SkalskiP** [comment]
Awesome! Appreciate it!

**Comment by SkalskiP** [comment]
Hi, @leayz-888! 👋🏻 The problem should be solved. I'm closing the issue, but feel free to reopen it if you will face more issues.
